#! /bin/bash

SIMON_DIR=${PWD}

rm -rf /usr/local/simon
mkdir /usr/local/simon

cd ../
zip -r app.zip app package.json nw.icns
mv app.zip /usr/local/simon/app.zip
cd /usr/local/simon/

cd ${SIMON_DIR}
zip simon.zip src/index.html package.json nw.icns
mv simon.zip ../.app/Contents/Resources/app.zip
open ../.app
