#! /bin/bash

APP_NAME=$1
PACKAGE_SCRIPT=$(cat scripts/package.json)
INDEX_HTML_SCRIPT=$(cat scripts/html/index.html)
BUILD_SCRIPT=$(cat scripts/build)

curl -O https://s3.amazonaws.com/node-webkit/v0.8.2/node-webkit-v0.8.2-osx-ia32.zip
mv node-webkit-v0.8.2-osx-ia32.zip ../node-webkit-v0.8.2-osx-ia32.zip
cd ..
unzip node-webkit-v0.8.2-osx-ia32.zip
rm node-webkit-v0.8.2-osx-ia32.zip
mv node-webkit.app ${APP_NAME}.app

echo ${PACKAGE_SCRIPT} >> package.json
mkdir app
cd app
mkdir assets
mkdir pages
touch index.html
echo ${INDEX_HTML_SCRIPT} >> index.html
cd ../simon
touch build
echo ${BUILD_SCRIPT} >> build
chmod 0777 build
